// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventstore.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Build struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	JobId                int32                `protobuf:"varint,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobName              string               `protobuf:"bytes,4,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	PipelineId           int32                `protobuf:"varint,5,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	PipelineName         string               `protobuf:"bytes,6,opt,name=pipeline_name,json=pipelineName,proto3" json:"pipeline_name,omitempty"`
	TeamId               int32                `protobuf:"varint,7,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TeamName             string               `protobuf:"bytes,8,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	Status               string               `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,11,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsCompleted          bool                 `protobuf:"varint,12,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	RerunOf              int32                `protobuf:"varint,13,opt,name=rerun_of,json=rerunOf,proto3" json:"rerun_of,omitempty"`
	RerunOfName          string               `protobuf:"bytes,14,opt,name=rerun_of_name,json=rerunOfName,proto3" json:"rerun_of_name,omitempty"`
	RerunNumber          int32                `protobuf:"varint,15,opt,name=rerun_number,json=rerunNumber,proto3" json:"rerun_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{0}
}

func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (m *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(m, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

func (m *Build) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Build) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Build) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *Build) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *Build) GetPipelineId() int32 {
	if m != nil {
		return m.PipelineId
	}
	return 0
}

func (m *Build) GetPipelineName() string {
	if m != nil {
		return m.PipelineName
	}
	return ""
}

func (m *Build) GetTeamId() int32 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *Build) GetTeamName() string {
	if m != nil {
		return m.TeamName
	}
	return ""
}

func (m *Build) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Build) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Build) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *Build) GetIsCompleted() bool {
	if m != nil {
		return m.IsCompleted
	}
	return false
}

func (m *Build) GetRerunOf() int32 {
	if m != nil {
		return m.RerunOf
	}
	return 0
}

func (m *Build) GetRerunOfName() string {
	if m != nil {
		return m.RerunOfName
	}
	return ""
}

func (m *Build) GetRerunNumber() int32 {
	if m != nil {
		return m.RerunNumber
	}
	return 0
}

type Pipeline struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TeamId               int32    `protobuf:"varint,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TeamName             string   `protobuf:"bytes,4,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pipeline) Reset()         { *m = Pipeline{} }
func (m *Pipeline) String() string { return proto.CompactTextString(m) }
func (*Pipeline) ProtoMessage()    {}
func (*Pipeline) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{1}
}

func (m *Pipeline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pipeline.Unmarshal(m, b)
}
func (m *Pipeline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pipeline.Marshal(b, m, deterministic)
}
func (m *Pipeline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pipeline.Merge(m, src)
}
func (m *Pipeline) XXX_Size() int {
	return xxx_messageInfo_Pipeline.Size(m)
}
func (m *Pipeline) XXX_DiscardUnknown() {
	xxx_messageInfo_Pipeline.DiscardUnknown(m)
}

var xxx_messageInfo_Pipeline proto.InternalMessageInfo

func (m *Pipeline) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pipeline) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pipeline) GetTeamId() int32 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *Pipeline) GetTeamName() string {
	if m != nil {
		return m.TeamName
	}
	return ""
}

type Team struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{2}
}

func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (m *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(m, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Event struct {
	Event                string   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{3}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *Event) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Key struct {
	Values               []int64  `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{4}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetValues() []int64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type Setup struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Setup) Reset()         { *m = Setup{} }
func (m *Setup) String() string { return proto.CompactTextString(m) }
func (*Setup) ProtoMessage()    {}
func (*Setup) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{5}
}

func (m *Setup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Setup.Unmarshal(m, b)
}
func (m *Setup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Setup.Marshal(b, m, deterministic)
}
func (m *Setup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Setup.Merge(m, src)
}
func (m *Setup) XXX_Size() int {
	return xxx_messageInfo_Setup.Size(m)
}
func (m *Setup) XXX_DiscardUnknown() {
	xxx_messageInfo_Setup.DiscardUnknown(m)
}

var xxx_messageInfo_Setup proto.InternalMessageInfo

type Setup_Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Setup_Request) Reset()         { *m = Setup_Request{} }
func (m *Setup_Request) String() string { return proto.CompactTextString(m) }
func (*Setup_Request) ProtoMessage()    {}
func (*Setup_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{5, 0}
}

func (m *Setup_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Setup_Request.Unmarshal(m, b)
}
func (m *Setup_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Setup_Request.Marshal(b, m, deterministic)
}
func (m *Setup_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Setup_Request.Merge(m, src)
}
func (m *Setup_Request) XXX_Size() int {
	return xxx_messageInfo_Setup_Request.Size(m)
}
func (m *Setup_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Setup_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Setup_Request proto.InternalMessageInfo

type Setup_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Setup_Response) Reset()         { *m = Setup_Response{} }
func (m *Setup_Response) String() string { return proto.CompactTextString(m) }
func (*Setup_Response) ProtoMessage()    {}
func (*Setup_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{5, 1}
}

func (m *Setup_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Setup_Response.Unmarshal(m, b)
}
func (m *Setup_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Setup_Response.Marshal(b, m, deterministic)
}
func (m *Setup_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Setup_Response.Merge(m, src)
}
func (m *Setup_Response) XXX_Size() int {
	return xxx_messageInfo_Setup_Response.Size(m)
}
func (m *Setup_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Setup_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Setup_Response proto.InternalMessageInfo

type Close struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Close) Reset()         { *m = Close{} }
func (m *Close) String() string { return proto.CompactTextString(m) }
func (*Close) ProtoMessage()    {}
func (*Close) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{6}
}

func (m *Close) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Close.Unmarshal(m, b)
}
func (m *Close) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Close.Marshal(b, m, deterministic)
}
func (m *Close) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Close.Merge(m, src)
}
func (m *Close) XXX_Size() int {
	return xxx_messageInfo_Close.Size(m)
}
func (m *Close) XXX_DiscardUnknown() {
	xxx_messageInfo_Close.DiscardUnknown(m)
}

var xxx_messageInfo_Close proto.InternalMessageInfo

type Close_Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Close_Request) Reset()         { *m = Close_Request{} }
func (m *Close_Request) String() string { return proto.CompactTextString(m) }
func (*Close_Request) ProtoMessage()    {}
func (*Close_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{6, 0}
}

func (m *Close_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Close_Request.Unmarshal(m, b)
}
func (m *Close_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Close_Request.Marshal(b, m, deterministic)
}
func (m *Close_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Close_Request.Merge(m, src)
}
func (m *Close_Request) XXX_Size() int {
	return xxx_messageInfo_Close_Request.Size(m)
}
func (m *Close_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Close_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Close_Request proto.InternalMessageInfo

type Close_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Close_Response) Reset()         { *m = Close_Response{} }
func (m *Close_Response) String() string { return proto.CompactTextString(m) }
func (*Close_Response) ProtoMessage()    {}
func (*Close_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{6, 1}
}

func (m *Close_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Close_Response.Unmarshal(m, b)
}
func (m *Close_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Close_Response.Marshal(b, m, deterministic)
}
func (m *Close_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Close_Response.Merge(m, src)
}
func (m *Close_Response) XXX_Size() int {
	return xxx_messageInfo_Close_Response.Size(m)
}
func (m *Close_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Close_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Close_Response proto.InternalMessageInfo

type Initialize struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Initialize) Reset()         { *m = Initialize{} }
func (m *Initialize) String() string { return proto.CompactTextString(m) }
func (*Initialize) ProtoMessage()    {}
func (*Initialize) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{7}
}

func (m *Initialize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Initialize.Unmarshal(m, b)
}
func (m *Initialize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Initialize.Marshal(b, m, deterministic)
}
func (m *Initialize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Initialize.Merge(m, src)
}
func (m *Initialize) XXX_Size() int {
	return xxx_messageInfo_Initialize.Size(m)
}
func (m *Initialize) XXX_DiscardUnknown() {
	xxx_messageInfo_Initialize.DiscardUnknown(m)
}

var xxx_messageInfo_Initialize proto.InternalMessageInfo

type Initialize_Request struct {
	Build                *Build   `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Initialize_Request) Reset()         { *m = Initialize_Request{} }
func (m *Initialize_Request) String() string { return proto.CompactTextString(m) }
func (*Initialize_Request) ProtoMessage()    {}
func (*Initialize_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{7, 0}
}

func (m *Initialize_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Initialize_Request.Unmarshal(m, b)
}
func (m *Initialize_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Initialize_Request.Marshal(b, m, deterministic)
}
func (m *Initialize_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Initialize_Request.Merge(m, src)
}
func (m *Initialize_Request) XXX_Size() int {
	return xxx_messageInfo_Initialize_Request.Size(m)
}
func (m *Initialize_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Initialize_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Initialize_Request proto.InternalMessageInfo

func (m *Initialize_Request) GetBuild() *Build {
	if m != nil {
		return m.Build
	}
	return nil
}

type Initialize_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Initialize_Response) Reset()         { *m = Initialize_Response{} }
func (m *Initialize_Response) String() string { return proto.CompactTextString(m) }
func (*Initialize_Response) ProtoMessage()    {}
func (*Initialize_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{7, 1}
}

func (m *Initialize_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Initialize_Response.Unmarshal(m, b)
}
func (m *Initialize_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Initialize_Response.Marshal(b, m, deterministic)
}
func (m *Initialize_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Initialize_Response.Merge(m, src)
}
func (m *Initialize_Response) XXX_Size() int {
	return xxx_messageInfo_Initialize_Response.Size(m)
}
func (m *Initialize_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Initialize_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Initialize_Response proto.InternalMessageInfo

type Finalize struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Finalize) Reset()         { *m = Finalize{} }
func (m *Finalize) String() string { return proto.CompactTextString(m) }
func (*Finalize) ProtoMessage()    {}
func (*Finalize) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{8}
}

func (m *Finalize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Finalize.Unmarshal(m, b)
}
func (m *Finalize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Finalize.Marshal(b, m, deterministic)
}
func (m *Finalize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Finalize.Merge(m, src)
}
func (m *Finalize) XXX_Size() int {
	return xxx_messageInfo_Finalize.Size(m)
}
func (m *Finalize) XXX_DiscardUnknown() {
	xxx_messageInfo_Finalize.DiscardUnknown(m)
}

var xxx_messageInfo_Finalize proto.InternalMessageInfo

type Finalize_Request struct {
	Build                *Build   `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Finalize_Request) Reset()         { *m = Finalize_Request{} }
func (m *Finalize_Request) String() string { return proto.CompactTextString(m) }
func (*Finalize_Request) ProtoMessage()    {}
func (*Finalize_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{8, 0}
}

func (m *Finalize_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Finalize_Request.Unmarshal(m, b)
}
func (m *Finalize_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Finalize_Request.Marshal(b, m, deterministic)
}
func (m *Finalize_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Finalize_Request.Merge(m, src)
}
func (m *Finalize_Request) XXX_Size() int {
	return xxx_messageInfo_Finalize_Request.Size(m)
}
func (m *Finalize_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Finalize_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Finalize_Request proto.InternalMessageInfo

func (m *Finalize_Request) GetBuild() *Build {
	if m != nil {
		return m.Build
	}
	return nil
}

type Finalize_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Finalize_Response) Reset()         { *m = Finalize_Response{} }
func (m *Finalize_Response) String() string { return proto.CompactTextString(m) }
func (*Finalize_Response) ProtoMessage()    {}
func (*Finalize_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{8, 1}
}

func (m *Finalize_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Finalize_Response.Unmarshal(m, b)
}
func (m *Finalize_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Finalize_Response.Marshal(b, m, deterministic)
}
func (m *Finalize_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Finalize_Response.Merge(m, src)
}
func (m *Finalize_Response) XXX_Size() int {
	return xxx_messageInfo_Finalize_Response.Size(m)
}
func (m *Finalize_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Finalize_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Finalize_Response proto.InternalMessageInfo

type Put struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Put) Reset()         { *m = Put{} }
func (m *Put) String() string { return proto.CompactTextString(m) }
func (*Put) ProtoMessage()    {}
func (*Put) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{9}
}

func (m *Put) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Put.Unmarshal(m, b)
}
func (m *Put) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Put.Marshal(b, m, deterministic)
}
func (m *Put) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Put.Merge(m, src)
}
func (m *Put) XXX_Size() int {
	return xxx_messageInfo_Put.Size(m)
}
func (m *Put) XXX_DiscardUnknown() {
	xxx_messageInfo_Put.DiscardUnknown(m)
}

var xxx_messageInfo_Put proto.InternalMessageInfo

type Put_Request struct {
	Build                *Build   `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	Events               []*Event `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Put_Request) Reset()         { *m = Put_Request{} }
func (m *Put_Request) String() string { return proto.CompactTextString(m) }
func (*Put_Request) ProtoMessage()    {}
func (*Put_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{9, 0}
}

func (m *Put_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Put_Request.Unmarshal(m, b)
}
func (m *Put_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Put_Request.Marshal(b, m, deterministic)
}
func (m *Put_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Put_Request.Merge(m, src)
}
func (m *Put_Request) XXX_Size() int {
	return xxx_messageInfo_Put_Request.Size(m)
}
func (m *Put_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Put_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Put_Request proto.InternalMessageInfo

func (m *Put_Request) GetBuild() *Build {
	if m != nil {
		return m.Build
	}
	return nil
}

func (m *Put_Request) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Put_Response struct {
	Key                  *Key     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Put_Response) Reset()         { *m = Put_Response{} }
func (m *Put_Response) String() string { return proto.CompactTextString(m) }
func (*Put_Response) ProtoMessage()    {}
func (*Put_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{9, 1}
}

func (m *Put_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Put_Response.Unmarshal(m, b)
}
func (m *Put_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Put_Response.Marshal(b, m, deterministic)
}
func (m *Put_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Put_Response.Merge(m, src)
}
func (m *Put_Response) XXX_Size() int {
	return xxx_messageInfo_Put_Response.Size(m)
}
func (m *Put_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Put_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Put_Response proto.InternalMessageInfo

func (m *Put_Response) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

type Get struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Get) Reset()         { *m = Get{} }
func (m *Get) String() string { return proto.CompactTextString(m) }
func (*Get) ProtoMessage()    {}
func (*Get) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{10}
}

func (m *Get) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Get.Unmarshal(m, b)
}
func (m *Get) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Get.Marshal(b, m, deterministic)
}
func (m *Get) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Get.Merge(m, src)
}
func (m *Get) XXX_Size() int {
	return xxx_messageInfo_Get.Size(m)
}
func (m *Get) XXX_DiscardUnknown() {
	xxx_messageInfo_Get.DiscardUnknown(m)
}

var xxx_messageInfo_Get proto.InternalMessageInfo

type Get_Request struct {
	Build                *Build   `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	Requested            int32    `protobuf:"varint,2,opt,name=requested,proto3" json:"requested,omitempty"`
	Cursor               *Key     `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Get_Request) Reset()         { *m = Get_Request{} }
func (m *Get_Request) String() string { return proto.CompactTextString(m) }
func (*Get_Request) ProtoMessage()    {}
func (*Get_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{10, 0}
}

func (m *Get_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Get_Request.Unmarshal(m, b)
}
func (m *Get_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Get_Request.Marshal(b, m, deterministic)
}
func (m *Get_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Get_Request.Merge(m, src)
}
func (m *Get_Request) XXX_Size() int {
	return xxx_messageInfo_Get_Request.Size(m)
}
func (m *Get_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Get_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Get_Request proto.InternalMessageInfo

func (m *Get_Request) GetBuild() *Build {
	if m != nil {
		return m.Build
	}
	return nil
}

func (m *Get_Request) GetRequested() int32 {
	if m != nil {
		return m.Requested
	}
	return 0
}

func (m *Get_Request) GetCursor() *Key {
	if m != nil {
		return m.Cursor
	}
	return nil
}

type Get_Response struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Cursor               *Key     `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Get_Response) Reset()         { *m = Get_Response{} }
func (m *Get_Response) String() string { return proto.CompactTextString(m) }
func (*Get_Response) ProtoMessage()    {}
func (*Get_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{10, 1}
}

func (m *Get_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Get_Response.Unmarshal(m, b)
}
func (m *Get_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Get_Response.Marshal(b, m, deterministic)
}
func (m *Get_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Get_Response.Merge(m, src)
}
func (m *Get_Response) XXX_Size() int {
	return xxx_messageInfo_Get_Response.Size(m)
}
func (m *Get_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Get_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Get_Response proto.InternalMessageInfo

func (m *Get_Response) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *Get_Response) GetCursor() *Key {
	if m != nil {
		return m.Cursor
	}
	return nil
}

type Delete struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delete) Reset()         { *m = Delete{} }
func (m *Delete) String() string { return proto.CompactTextString(m) }
func (*Delete) ProtoMessage()    {}
func (*Delete) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{11}
}

func (m *Delete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delete.Unmarshal(m, b)
}
func (m *Delete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delete.Marshal(b, m, deterministic)
}
func (m *Delete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delete.Merge(m, src)
}
func (m *Delete) XXX_Size() int {
	return xxx_messageInfo_Delete.Size(m)
}
func (m *Delete) XXX_DiscardUnknown() {
	xxx_messageInfo_Delete.DiscardUnknown(m)
}

var xxx_messageInfo_Delete proto.InternalMessageInfo

type Delete_Request struct {
	Builds               []*Build `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delete_Request) Reset()         { *m = Delete_Request{} }
func (m *Delete_Request) String() string { return proto.CompactTextString(m) }
func (*Delete_Request) ProtoMessage()    {}
func (*Delete_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{11, 0}
}

func (m *Delete_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delete_Request.Unmarshal(m, b)
}
func (m *Delete_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delete_Request.Marshal(b, m, deterministic)
}
func (m *Delete_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delete_Request.Merge(m, src)
}
func (m *Delete_Request) XXX_Size() int {
	return xxx_messageInfo_Delete_Request.Size(m)
}
func (m *Delete_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Delete_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Delete_Request proto.InternalMessageInfo

func (m *Delete_Request) GetBuilds() []*Build {
	if m != nil {
		return m.Builds
	}
	return nil
}

type Delete_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delete_Response) Reset()         { *m = Delete_Response{} }
func (m *Delete_Response) String() string { return proto.CompactTextString(m) }
func (*Delete_Response) ProtoMessage()    {}
func (*Delete_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{11, 1}
}

func (m *Delete_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delete_Response.Unmarshal(m, b)
}
func (m *Delete_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delete_Response.Marshal(b, m, deterministic)
}
func (m *Delete_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delete_Response.Merge(m, src)
}
func (m *Delete_Response) XXX_Size() int {
	return xxx_messageInfo_Delete_Response.Size(m)
}
func (m *Delete_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Delete_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Delete_Response proto.InternalMessageInfo

type DeletePipeline struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePipeline) Reset()         { *m = DeletePipeline{} }
func (m *DeletePipeline) String() string { return proto.CompactTextString(m) }
func (*DeletePipeline) ProtoMessage()    {}
func (*DeletePipeline) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{12}
}

func (m *DeletePipeline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePipeline.Unmarshal(m, b)
}
func (m *DeletePipeline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePipeline.Marshal(b, m, deterministic)
}
func (m *DeletePipeline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePipeline.Merge(m, src)
}
func (m *DeletePipeline) XXX_Size() int {
	return xxx_messageInfo_DeletePipeline.Size(m)
}
func (m *DeletePipeline) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePipeline.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePipeline proto.InternalMessageInfo

type DeletePipeline_Request struct {
	Pipeline             *Pipeline `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeletePipeline_Request) Reset()         { *m = DeletePipeline_Request{} }
func (m *DeletePipeline_Request) String() string { return proto.CompactTextString(m) }
func (*DeletePipeline_Request) ProtoMessage()    {}
func (*DeletePipeline_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{12, 0}
}

func (m *DeletePipeline_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePipeline_Request.Unmarshal(m, b)
}
func (m *DeletePipeline_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePipeline_Request.Marshal(b, m, deterministic)
}
func (m *DeletePipeline_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePipeline_Request.Merge(m, src)
}
func (m *DeletePipeline_Request) XXX_Size() int {
	return xxx_messageInfo_DeletePipeline_Request.Size(m)
}
func (m *DeletePipeline_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePipeline_Request.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePipeline_Request proto.InternalMessageInfo

func (m *DeletePipeline_Request) GetPipeline() *Pipeline {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

type DeletePipeline_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePipeline_Response) Reset()         { *m = DeletePipeline_Response{} }
func (m *DeletePipeline_Response) String() string { return proto.CompactTextString(m) }
func (*DeletePipeline_Response) ProtoMessage()    {}
func (*DeletePipeline_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{12, 1}
}

func (m *DeletePipeline_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePipeline_Response.Unmarshal(m, b)
}
func (m *DeletePipeline_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePipeline_Response.Marshal(b, m, deterministic)
}
func (m *DeletePipeline_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePipeline_Response.Merge(m, src)
}
func (m *DeletePipeline_Response) XXX_Size() int {
	return xxx_messageInfo_DeletePipeline_Response.Size(m)
}
func (m *DeletePipeline_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePipeline_Response.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePipeline_Response proto.InternalMessageInfo

type DeleteTeam struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTeam) Reset()         { *m = DeleteTeam{} }
func (m *DeleteTeam) String() string { return proto.CompactTextString(m) }
func (*DeleteTeam) ProtoMessage()    {}
func (*DeleteTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{13}
}

func (m *DeleteTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTeam.Unmarshal(m, b)
}
func (m *DeleteTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTeam.Marshal(b, m, deterministic)
}
func (m *DeleteTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTeam.Merge(m, src)
}
func (m *DeleteTeam) XXX_Size() int {
	return xxx_messageInfo_DeleteTeam.Size(m)
}
func (m *DeleteTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTeam.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTeam proto.InternalMessageInfo

type DeleteTeam_Request struct {
	Team                 *Team    `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTeam_Request) Reset()         { *m = DeleteTeam_Request{} }
func (m *DeleteTeam_Request) String() string { return proto.CompactTextString(m) }
func (*DeleteTeam_Request) ProtoMessage()    {}
func (*DeleteTeam_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{13, 0}
}

func (m *DeleteTeam_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTeam_Request.Unmarshal(m, b)
}
func (m *DeleteTeam_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTeam_Request.Marshal(b, m, deterministic)
}
func (m *DeleteTeam_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTeam_Request.Merge(m, src)
}
func (m *DeleteTeam_Request) XXX_Size() int {
	return xxx_messageInfo_DeleteTeam_Request.Size(m)
}
func (m *DeleteTeam_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTeam_Request.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTeam_Request proto.InternalMessageInfo

func (m *DeleteTeam_Request) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

type DeleteTeam_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTeam_Response) Reset()         { *m = DeleteTeam_Response{} }
func (m *DeleteTeam_Response) String() string { return proto.CompactTextString(m) }
func (*DeleteTeam_Response) ProtoMessage()    {}
func (*DeleteTeam_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{13, 1}
}

func (m *DeleteTeam_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTeam_Response.Unmarshal(m, b)
}
func (m *DeleteTeam_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTeam_Response.Marshal(b, m, deterministic)
}
func (m *DeleteTeam_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTeam_Response.Merge(m, src)
}
func (m *DeleteTeam_Response) XXX_Size() int {
	return xxx_messageInfo_DeleteTeam_Response.Size(m)
}
func (m *DeleteTeam_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTeam_Response.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTeam_Response proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Build)(nil), "proto.Build")
	proto.RegisterType((*Pipeline)(nil), "proto.Pipeline")
	proto.RegisterType((*Team)(nil), "proto.Team")
	proto.RegisterType((*Event)(nil), "proto.Event")
	proto.RegisterType((*Key)(nil), "proto.Key")
	proto.RegisterType((*Setup)(nil), "proto.Setup")
	proto.RegisterType((*Setup_Request)(nil), "proto.Setup.Request")
	proto.RegisterType((*Setup_Response)(nil), "proto.Setup.Response")
	proto.RegisterType((*Close)(nil), "proto.Close")
	proto.RegisterType((*Close_Request)(nil), "proto.Close.Request")
	proto.RegisterType((*Close_Response)(nil), "proto.Close.Response")
	proto.RegisterType((*Initialize)(nil), "proto.Initialize")
	proto.RegisterType((*Initialize_Request)(nil), "proto.Initialize.Request")
	proto.RegisterType((*Initialize_Response)(nil), "proto.Initialize.Response")
	proto.RegisterType((*Finalize)(nil), "proto.Finalize")
	proto.RegisterType((*Finalize_Request)(nil), "proto.Finalize.Request")
	proto.RegisterType((*Finalize_Response)(nil), "proto.Finalize.Response")
	proto.RegisterType((*Put)(nil), "proto.Put")
	proto.RegisterType((*Put_Request)(nil), "proto.Put.Request")
	proto.RegisterType((*Put_Response)(nil), "proto.Put.Response")
	proto.RegisterType((*Get)(nil), "proto.Get")
	proto.RegisterType((*Get_Request)(nil), "proto.Get.Request")
	proto.RegisterType((*Get_Response)(nil), "proto.Get.Response")
	proto.RegisterType((*Delete)(nil), "proto.Delete")
	proto.RegisterType((*Delete_Request)(nil), "proto.Delete.Request")
	proto.RegisterType((*Delete_Response)(nil), "proto.Delete.Response")
	proto.RegisterType((*DeletePipeline)(nil), "proto.DeletePipeline")
	proto.RegisterType((*DeletePipeline_Request)(nil), "proto.DeletePipeline.Request")
	proto.RegisterType((*DeletePipeline_Response)(nil), "proto.DeletePipeline.Response")
	proto.RegisterType((*DeleteTeam)(nil), "proto.DeleteTeam")
	proto.RegisterType((*DeleteTeam_Request)(nil), "proto.DeleteTeam.Request")
	proto.RegisterType((*DeleteTeam_Response)(nil), "proto.DeleteTeam.Response")
}

func init() { proto.RegisterFile("eventstore.proto", fileDescriptor_00783576c07562d6) }

var fileDescriptor_00783576c07562d6 = []byte{
	// 817 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x4e, 0xf3, 0x46,
	0x14, 0x95, 0xe3, 0xd8, 0x71, 0x6e, 0x02, 0x5f, 0x35, 0xfd, 0x7e, 0x8c, 0xcb, 0x4f, 0x70, 0x59,
	0x44, 0x54, 0x0d, 0x12, 0xa5, 0xad, 0xba, 0xe8, 0xa6, 0x40, 0xa3, 0x08, 0x09, 0x90, 0xc9, 0x3e,
	0x72, 0xf0, 0x05, 0x99, 0x26, 0x76, 0x6a, 0x8f, 0x91, 0xe8, 0xba, 0x6f, 0xd3, 0x57, 0xe9, 0x83,
	0xf4, 0x31, 0xaa, 0xb9, 0x33, 0x63, 0xc7, 0x49, 0xa3, 0x82, 0xbe, 0x55, 0x7c, 0xcf, 0x3d, 0xe7,
	0x78, 0xe6, 0xcc, 0x5c, 0x07, 0xbe, 0xc0, 0x67, 0x4c, 0x78, 0xce, 0xd3, 0x0c, 0x07, 0x8b, 0x2c,
	0xe5, 0x29, 0xb3, 0xe8, 0xc7, 0x3b, 0x78, 0x4c, 0xd3, 0xc7, 0x19, 0x9e, 0x50, 0x35, 0x2d, 0x1e,
	0x4e, 0x78, 0x3c, 0xc7, 0x9c, 0x87, 0xf3, 0x85, 0xe4, 0xf9, 0xff, 0x98, 0x60, 0xfd, 0x52, 0xc4,
	0xb3, 0x88, 0x6d, 0x43, 0x23, 0x8e, 0x5c, 0xa3, 0x67, 0xf4, 0xad, 0xa0, 0x11, 0x47, 0x8c, 0x41,
	0x33, 0x09, 0xe7, 0xe8, 0x36, 0x7a, 0x46, 0xbf, 0x1d, 0xd0, 0x33, 0xfb, 0x00, 0xf6, 0x53, 0x3a,
	0x9d, 0xc4, 0x91, 0x6b, 0x12, 0xcf, 0x7a, 0x4a, 0xa7, 0xa3, 0x88, 0xed, 0x80, 0x23, 0x60, 0xa2,
	0x37, 0x89, 0xde, 0x7a, 0x4a, 0xa7, 0xd7, 0x42, 0x71, 0x00, 0x9d, 0x45, 0xbc, 0xc0, 0x59, 0x9c,
	0xa0, 0x90, 0x59, 0x24, 0x03, 0x0d, 0x8d, 0x22, 0xf6, 0x35, 0x6c, 0x95, 0x04, 0x32, 0xb0, 0xc9,
	0xa0, 0xab, 0x41, 0x72, 0xf9, 0x04, 0x2d, 0x8e, 0xe1, 0x5c, 0x38, 0xb4, 0xc8, 0xc1, 0x16, 0xe5,
	0x28, 0x62, 0x5f, 0x41, 0x9b, 0x1a, 0xa4, 0x74, 0x48, 0xe9, 0x08, 0x80, 0x54, 0x1f, 0xc1, 0xce,
	0x79, 0xc8, 0x8b, 0xdc, 0x6d, 0x53, 0x47, 0x55, 0xec, 0x27, 0x80, 0x9c, 0x87, 0x19, 0x9f, 0x88,
	0x30, 0x5c, 0xe8, 0x19, 0xfd, 0xce, 0xa9, 0x37, 0x90, 0x49, 0x0d, 0x74, 0x52, 0x83, 0xb1, 0x4e,
	0x2a, 0x68, 0x13, 0x5b, 0xd4, 0xec, 0x7b, 0x70, 0x30, 0x89, 0xa4, 0xb0, 0xf3, 0xbf, 0xc2, 0x16,
	0x26, 0x11, 0xc9, 0x0e, 0xa1, 0x1b, 0xe7, 0x93, 0xfb, 0x74, 0xbe, 0x98, 0x21, 0xc7, 0xc8, 0xed,
	0xf6, 0x8c, 0xbe, 0x13, 0x74, 0xe2, 0xfc, 0x5c, 0x43, 0x22, 0xc3, 0x0c, 0xb3, 0x22, 0x99, 0xa4,
	0x0f, 0xee, 0x16, 0xed, 0xb1, 0x45, 0xf5, 0xcd, 0x03, 0xf3, 0x61, 0x4b, 0xb7, 0xe4, 0x46, 0xb7,
	0x69, 0x3b, 0x1d, 0xd5, 0xa7, 0xbd, 0x1e, 0x42, 0x57, 0x72, 0x92, 0x62, 0x3e, 0xc5, 0xcc, 0x7d,
	0x47, 0x16, 0x92, 0x72, 0x4d, 0x90, 0x1f, 0x81, 0x73, 0xab, 0x42, 0x7d, 0xd5, 0x61, 0x2f, 0x85,
	0x6e, 0x6e, 0x0e, 0xbd, 0x59, 0x0f, 0xdd, 0x3f, 0x86, 0xe6, 0x18, 0xc3, 0xf9, 0x6b, 0xde, 0xe0,
	0x5f, 0x81, 0x75, 0x29, 0x2e, 0x2e, 0x7b, 0x0f, 0x16, 0xdd, 0x60, 0xe2, 0xb7, 0x03, 0x59, 0x30,
	0x17, 0x5a, 0xcf, 0x98, 0xe5, 0x71, 0x9a, 0x28, 0x95, 0x2e, 0x85, 0x59, 0x14, 0xf2, 0x90, 0xd6,
	0xd5, 0x0d, 0xe8, 0xd9, 0xdf, 0x03, 0xf3, 0x0a, 0x5f, 0xc4, 0xa1, 0x3f, 0x87, 0xb3, 0x02, 0x73,
	0xd7, 0xe8, 0x99, 0x7d, 0x33, 0x50, 0x95, 0xbf, 0x0f, 0xd6, 0x1d, 0xf2, 0x62, 0xe1, 0xb5, 0xa1,
	0x15, 0xe0, 0xef, 0x05, 0xe6, 0xdc, 0x03, 0x70, 0x02, 0xcc, 0x17, 0x69, 0x92, 0xa3, 0xe8, 0x9f,
	0xcf, 0xd2, 0x1c, 0x37, 0xf5, 0x87, 0x00, 0xa3, 0x24, 0xe6, 0x71, 0x38, 0x8b, 0xff, 0x40, 0xef,
	0xdb, 0x92, 0xc4, 0x7c, 0xb0, 0xa6, 0x62, 0x80, 0x68, 0xed, 0x9d, 0xd3, 0xae, 0xbc, 0x08, 0x03,
	0x1a, 0xaa, 0x40, 0xb6, 0x6a, 0x46, 0x97, 0xe0, 0xfc, 0x1a, 0x27, 0x9f, 0x6d, 0xf3, 0xa7, 0x01,
	0xe6, 0x6d, 0xc1, 0xbd, 0xbb, 0x37, 0x59, 0xb0, 0x23, 0xb0, 0xe5, 0xb7, 0xc2, 0x6d, 0xf4, 0xcc,
	0x25, 0x12, 0x9d, 0x43, 0xa0, 0x7a, 0x5e, 0xbf, 0x7a, 0x11, 0xdb, 0x05, 0xf3, 0x37, 0x7c, 0x51,
	0x9e, 0xa0, 0xe8, 0x57, 0xf8, 0x12, 0x08, 0xd8, 0xff, 0xdb, 0x00, 0x73, 0x88, 0xdc, 0x4b, 0xdf,
	0xb6, 0x8c, 0x5d, 0x68, 0x67, 0x92, 0x8e, 0x11, 0x1d, 0xae, 0x15, 0x54, 0x00, 0xf3, 0xc1, 0xbe,
	0x2f, 0xb2, 0x3c, 0xcd, 0xe8, 0x80, 0xeb, 0x6f, 0x55, 0x1d, 0x6f, 0xbc, 0xb4, 0xc4, 0x6a, 0x53,
	0xc6, 0xe6, 0x4d, 0x2d, 0xb9, 0x36, 0x36, 0xb9, 0xfa, 0x97, 0x60, 0x5f, 0xa0, 0x18, 0x48, 0xef,
	0xa4, 0xda, 0xd0, 0x11, 0xd8, 0xb4, 0xea, 0x55, 0x7b, 0xb9, 0x23, 0xd5, 0xab, 0x1d, 0xce, 0x18,
	0xb6, 0xa5, 0x8d, 0x1e, 0x38, 0xef, 0x87, 0xca, 0xee, 0x1b, 0x70, 0xf4, 0xc7, 0x4d, 0x45, 0xf4,
	0x4e, 0x19, 0x6a, 0x76, 0x50, 0x12, 0x6a, 0xae, 0x17, 0x00, 0xd2, 0x55, 0x0c, 0x98, 0x77, 0x5c,
	0x39, 0x1e, 0x40, 0x53, 0xcc, 0x9f, 0x72, 0xeb, 0x28, 0x37, 0xc1, 0x0a, 0xa8, 0xb1, 0xec, 0x72,
	0xfa, 0x57, 0x13, 0x80, 0x82, 0xb9, 0x13, 0x7f, 0x17, 0xec, 0x4c, 0xcd, 0x05, 0x7b, 0xaf, 0x64,
	0x54, 0x0d, 0xf4, 0x08, 0x7c, 0x58, 0x41, 0x55, 0xe2, 0x67, 0x6a, 0x5a, 0x4a, 0x15, 0x55, 0x6b,
	0x2a, 0x8d, 0x2a, 0xd5, 0xf9, 0xf2, 0x0c, 0xb1, 0x1d, 0x45, 0xaa, 0xa0, 0x52, 0xef, 0xfd, 0x57,
	0x4b, 0x99, 0xfc, 0x5c, 0xcd, 0x0f, 0xfb, 0xa4, 0x78, 0x1a, 0x28, 0x0d, 0xdc, 0xf5, 0x86, 0x92,
	0x0f, 0x68, 0x6c, 0x18, 0xd3, 0x91, 0x17, 0xbc, 0x14, 0x7d, 0x59, 0xc3, 0x2a, 0xfe, 0x10, 0x2b,
	0xfe, 0x10, 0xd7, 0xf9, 0x12, 0x53, 0xfc, 0x1f, 0xf5, 0x0d, 0x62, 0x3a, 0x04, 0x59, 0x96, 0xaa,
	0x8f, 0xab, 0xb0, 0x12, 0xde, 0xac, 0xde, 0x19, 0xb6, 0x57, 0x63, 0x6a, 0xb8, 0x34, 0xda, 0xdf,
	0xd4, 0xae, 0xd2, 0xae, 0xae, 0x4b, 0x99, 0x76, 0x05, 0xad, 0xa5, 0x5d, 0x6b, 0x49, 0x93, 0xa9,
	0x4d, 0xad, 0xef, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x63, 0x52, 0x3f, 0x5f, 0x62, 0x08, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventStoreClient is the client API for EventStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventStoreClient interface {
	Setup(ctx context.Context, in *Setup_Request, opts ...grpc.CallOption) (*Setup_Response, error)
	Close(ctx context.Context, in *Close_Request, opts ...grpc.CallOption) (*Close_Response, error)
	Initialize(ctx context.Context, in *Initialize_Request, opts ...grpc.CallOption) (*Initialize_Response, error)
	Finalize(ctx context.Context, in *Finalize_Request, opts ...grpc.CallOption) (*Finalize_Response, error)
	Put(ctx context.Context, in *Put_Request, opts ...grpc.CallOption) (*Put_Response, error)
	Get(ctx context.Context, in *Get_Request, opts ...grpc.CallOption) (*Get_Response, error)
	Delete(ctx context.Context, in *Delete_Request, opts ...grpc.CallOption) (*Delete_Response, error)
	DeletePipeline(ctx context.Context, in *DeletePipeline_Request, opts ...grpc.CallOption) (*DeletePipeline_Response, error)
	DeleteTeam(ctx context.Context, in *DeleteTeam_Request, opts ...grpc.CallOption) (*DeleteTeam_Response, error)
}

type eventStoreClient struct {
	cc *grpc.ClientConn
}

func NewEventStoreClient(cc *grpc.ClientConn) EventStoreClient {
	return &eventStoreClient{cc}
}

func (c *eventStoreClient) Setup(ctx context.Context, in *Setup_Request, opts ...grpc.CallOption) (*Setup_Response, error) {
	out := new(Setup_Response)
	err := c.cc.Invoke(ctx, "/proto.EventStore/Setup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) Close(ctx context.Context, in *Close_Request, opts ...grpc.CallOption) (*Close_Response, error) {
	out := new(Close_Response)
	err := c.cc.Invoke(ctx, "/proto.EventStore/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) Initialize(ctx context.Context, in *Initialize_Request, opts ...grpc.CallOption) (*Initialize_Response, error) {
	out := new(Initialize_Response)
	err := c.cc.Invoke(ctx, "/proto.EventStore/Initialize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) Finalize(ctx context.Context, in *Finalize_Request, opts ...grpc.CallOption) (*Finalize_Response, error) {
	out := new(Finalize_Response)
	err := c.cc.Invoke(ctx, "/proto.EventStore/Finalize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) Put(ctx context.Context, in *Put_Request, opts ...grpc.CallOption) (*Put_Response, error) {
	out := new(Put_Response)
	err := c.cc.Invoke(ctx, "/proto.EventStore/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) Get(ctx context.Context, in *Get_Request, opts ...grpc.CallOption) (*Get_Response, error) {
	out := new(Get_Response)
	err := c.cc.Invoke(ctx, "/proto.EventStore/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) Delete(ctx context.Context, in *Delete_Request, opts ...grpc.CallOption) (*Delete_Response, error) {
	out := new(Delete_Response)
	err := c.cc.Invoke(ctx, "/proto.EventStore/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) DeletePipeline(ctx context.Context, in *DeletePipeline_Request, opts ...grpc.CallOption) (*DeletePipeline_Response, error) {
	out := new(DeletePipeline_Response)
	err := c.cc.Invoke(ctx, "/proto.EventStore/DeletePipeline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) DeleteTeam(ctx context.Context, in *DeleteTeam_Request, opts ...grpc.CallOption) (*DeleteTeam_Response, error) {
	out := new(DeleteTeam_Response)
	err := c.cc.Invoke(ctx, "/proto.EventStore/DeleteTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventStoreServer is the server API for EventStore service.
type EventStoreServer interface {
	Setup(context.Context, *Setup_Request) (*Setup_Response, error)
	Close(context.Context, *Close_Request) (*Close_Response, error)
	Initialize(context.Context, *Initialize_Request) (*Initialize_Response, error)
	Finalize(context.Context, *Finalize_Request) (*Finalize_Response, error)
	Put(context.Context, *Put_Request) (*Put_Response, error)
	Get(context.Context, *Get_Request) (*Get_Response, error)
	Delete(context.Context, *Delete_Request) (*Delete_Response, error)
	DeletePipeline(context.Context, *DeletePipeline_Request) (*DeletePipeline_Response, error)
	DeleteTeam(context.Context, *DeleteTeam_Request) (*DeleteTeam_Response, error)
}

// UnimplementedEventStoreServer can be embedded to have forward compatible implementations.
type UnimplementedEventStoreServer struct {
}

func (*UnimplementedEventStoreServer) Setup(ctx context.Context, req *Setup_Request) (*Setup_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Setup not implemented")
}
func (*UnimplementedEventStoreServer) Close(ctx context.Context, req *Close_Request) (*Close_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (*UnimplementedEventStoreServer) Initialize(ctx context.Context, req *Initialize_Request) (*Initialize_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initialize not implemented")
}
func (*UnimplementedEventStoreServer) Finalize(ctx context.Context, req *Finalize_Request) (*Finalize_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Finalize not implemented")
}
func (*UnimplementedEventStoreServer) Put(ctx context.Context, req *Put_Request) (*Put_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedEventStoreServer) Get(ctx context.Context, req *Get_Request) (*Get_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedEventStoreServer) Delete(ctx context.Context, req *Delete_Request) (*Delete_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedEventStoreServer) DeletePipeline(ctx context.Context, req *DeletePipeline_Request) (*DeletePipeline_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePipeline not implemented")
}
func (*UnimplementedEventStoreServer) DeleteTeam(ctx context.Context, req *DeleteTeam_Request) (*DeleteTeam_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTeam not implemented")
}

func RegisterEventStoreServer(s *grpc.Server, srv EventStoreServer) {
	s.RegisterService(&_EventStore_serviceDesc, srv)
}

func _EventStore_Setup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Setup_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Setup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventStore/Setup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Setup(ctx, req.(*Setup_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Close_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventStore/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Close(ctx, req.(*Close_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Initialize_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventStore/Initialize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Initialize(ctx, req.(*Initialize_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_Finalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Finalize_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Finalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventStore/Finalize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Finalize(ctx, req.(*Finalize_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Put_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventStore/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Put(ctx, req.(*Put_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Get_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventStore/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Get(ctx, req.(*Get_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Delete_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventStore/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Delete(ctx, req.(*Delete_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_DeletePipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePipeline_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).DeletePipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventStore/DeletePipeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).DeletePipeline(ctx, req.(*DeletePipeline_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_DeleteTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTeam_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).DeleteTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventStore/DeleteTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).DeleteTeam(ctx, req.(*DeleteTeam_Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EventStore",
	HandlerType: (*EventStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Setup",
			Handler:    _EventStore_Setup_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _EventStore_Close_Handler,
		},
		{
			MethodName: "Initialize",
			Handler:    _EventStore_Initialize_Handler,
		},
		{
			MethodName: "Finalize",
			Handler:    _EventStore_Finalize_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _EventStore_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _EventStore_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _EventStore_Delete_Handler,
		},
		{
			MethodName: "DeletePipeline",
			Handler:    _EventStore_DeletePipeline_Handler,
		},
		{
			MethodName: "DeleteTeam",
			Handler:    _EventStore_DeleteTeam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eventstore.proto",
}
